# Generated by Django 2.1.4 on 2019-01-15 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TemporeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='person',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='person',
            name='PersonId',
        ),
    ]
